version: "3.9"

services:
  db-test:
    image: postgres:14-alpine
    container_name: db-test-NotesAPI
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    env_file:
      - .test.env

volumes:
  postgres_test_data: